[package]
name = "xtask"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] } # "blocking" is simpler for scripts
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
